#ifndef KAGOME_WRAPPER_H
#define KAGOME_WRAPPER_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Kagome C Wrapper API
 *
 * This is the stable, public API for using Kagome from other languages.
 * All FFI users (Python, PHP, Rust, etc.) should call these functions.
 *
 * API Functions:
 * - kagome_init()              : Create a tokenizer
 * - kagome_destroy()           : Free a tokenizer
 * - kagome_tokenize()          : Tokenize text
 * - kagome_free_token_array()  : Free tokenization results
 *
 * Implementation Notes:
 * - These wrap Go-exported functions internally
 * - Only kagome_* symbols are visible (built with -fvisibility=hidden)
 * - Token and TokenArray types come from libkagome.h (auto-generated by Go)
 *
 * For FFI Users:
 * Define these structures in your language:
 *
 *   Token {
 *       surface: string       // Surface form (表層形)
 *       pos1: string          // Part-of-speech level 1, major (品詞大分類)
 *       pos2: string          // Part-of-speech level 2, middle (品詞中分類)
 *       pos3: string          // Part-of-speech level 3, small (品詞小分類)
 *       pos4: string          // Part-of-speech level 4, detailed (品詞再分類)
 *       base_form: string     // Base form (原形)
 *       conj_type: string     // Conjugation type (活用型)
 *       conj_form: string     // Conjugation form (活用形)
 *       reading: string       // Reading in katakana (読み)
 *       pronunciation: string // Pronunciation in katakana (発音)
 *       start: int            // Start position (開始位置)
 *       end: int              // End position (終了位置)
 *   }
 *
 *   TokenArray {
 *       tokens: pointer to Token array
 *       length: int
 *   }
 */

/*
 * Create a new tokenizer.
 *
 * Returns: Handle to tokenizer, or NULL on failure
 */
void* kagome_init(void);

/*
 * Free a tokenizer.
 *
 * handle: Tokenizer from kagome_init()
 *
 * Safe to call with NULL.
 */
void kagome_destroy(void* handle);

/*
 * Tokenize Japanese text.
 *
 * handle: Tokenizer from kagome_init()
 * input:  UTF-8 text (null-terminated)
 *
 * Returns: Array of tokens, or NULL on failure
 *
 * You MUST call kagome_free_token_array() to free the result.
 */
TokenArray* kagome_tokenize(void* handle, const char* input);

/*
 * Free tokenization results.
 *
 * arr: Result from kagome_tokenize()
 *
 * Safe to call with NULL.
 */
void kagome_free_token_array(TokenArray* arr);

/*
 * Echo a string (for testing FFI setup).
 *
 * This is a simple test function that copies the input string and returns it.
 * Useful for:
 * - Verifying the library loads correctly
 * - Testing string passing across FFI boundary
 * - Checking memory allocation/deallocation works
 * - Troubleshooting FFI issues before trying tokenization
 *
 * input: UTF-8 text (null-terminated)
 *
 * Returns: Copy of the input string, or NULL if input is NULL
 *
 * You MUST call kagome_echo_free() to free the result.
 */
char* kagome_echo(const char* input);

/*
 * Free string returned by kagome_echo().
 *
 * str: String from kagome_echo()
 *
 * Safe to call with NULL.
 */
void kagome_echo_free(char* str);

#ifdef __cplusplus
}
#endif

#endif /* KAGOME_WRAPPER_H */
