volumes:
  kagome-dist:

services:
  kagome-build:
    build:
      context: .
    volumes:
      - kagome-dist:/app/bin

  python-test:
    image: python:latest
    volumes:
      - kagome-dist:/app/bin
      - ./python3:/app/python3
    working_dir: /app
    entrypoint: ["/usr/local/bin/python3", "/app/python3/main.py"]
    depends_on:
      - kagome-build
