name: Reviewdog

on:
  pull_request:
    types: [opened, synchronize]
    paths: '**.go'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          reporter: github-pr-review
